version: "3"

services:

  mongodb:
    image: mongo:6.0
    volumes:
      - ./push-data.mongodb:/usr/src/push-data.mongodb:ro

  influxdb:
    image: influxdb:2.5
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=integration_tests_org
      - DOCKER_INFLUXDB_INIT_BUCKET=integration_tests_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=integration_tests_token

  mongodb-scraper:
    build: ..
    command:
      - /usr/local/bin/mongodb-scraper
      - --verbose
    environment:
      - INTERVAL=2s
      - MONGODB_DATABASE=testdb
      - MONGODB_COLLECTION=testcoll
      - INFLUXDB_API_TOKEN=integration_tests_token
      - INFLUXDB_ORG=integration_tests_org
      - INFLUXDB_BUCKET=integration_tests_bucket
